### ISSUE TITLE
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\ajay\\python\\Browser'

### ISSUE THREAD

**Issue by ajaysai-g** [chrisBrookes93/robotframework-remoterunner#19]
Hi,

Gettig below issue while running the  rfremoterun <ip> <path:C:----main.robot>

Could you please provide the solution?

C:\Users\ajay\python\robot\running\builder\builders.py:112: UserWarning: 'TestSuiteBuilder' argument 'included_suites' is deprecated and has no effect. Use the new 'included_files' argument or filter the created suite instead.
  warnings.warn("'TestSuiteBuilder' argument 'included_suites' is deprecated "
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\ajay\python\Scripts\rfremoterun.exe\__main__.py", line 7, in <module>
  File "C:\Users\ajay\python\rfremoterunner\executor.py", line 25, in run_executor
    result = rfs.execute_run(arg_parser.suites, arg_parser.extension, arg_parser.suite, arg_parser.robot_run_args)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ajay\python\rfremoterunner\rf_client.py", line 63, in execute_run
    self._package_suite_hierarchy(suite)
  File "C:\Users\ajay\python\rfremoterunner\rf_client.py", line 109, in _package_suite_hierarchy
    self._suites[suite_filename] = self._process_test_suite(suite)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ajay\python\rfremoterunner\rf_client.py", line 134, in _process_test_suite
    updated_file = self._process_robot_file(suite)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ajay\python\rfremoterunner\rf_client.py", line 191, in _process_robot_file
    self._dependencies[filename] = read_file_from_disk(full_path)
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ajay\python\rfremoterunner\utils.py", line 30, in read_file_from_disk
    with open(path, 'r', encoding=encoding) as file_handle:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\ajay\\python\\Browser'

**Comment by chrisBrookes93** [comment]
Hi @ajaysai-g, 

It looks to me like its a file permissions error, can you try running as an Administrator. 

If this doesn't work then can you please provide some more info, including:

- Version of Python
- Packages and versions installed
- Sample robot file
- Anything else that may be relevant

Thanks

**Comment by mardukbp** [comment]
The problem is that robotframework-remoterunner expects third-party libraries to be a single Python file, not a directory. It has been reported before (#16) and a PR fixing it (#17) was ignored. I just submitted a PR (#20) that fixes this and another problem.

@chrisBrookes93 Please take a look at this issue. Your library is very useful, but in its current state it is unusable for most people.
